### ISSUE TITLE
Adjusting servo end courses and speed (delay)

### ISSUE THREAD

**Issue by vef445** [jlecomte/automated-telescope-dust-cover#11]
Hi,
First of all, be aware that I'm in no way a professional developer :)

With the driver you built, I wasn't able to get the full course of my 270deg. servo. A quick investigation revealed that the default values provided by Servo.h when attaching the servo (min pulse width = 544 and max pulse width = 2400) were not ideal for my setup. (Using the cheap servos from Amazon that you listed).

Instead of just editing the Arduino code with alternative (and fixed) values, I decided to add 'pulse min' and 'pulse max' as part of the Ascom driver profile.
![Screenshot 2024-06-17 111642](https://github.com/jlecomte/ascom-telescope-cover/assets/5900426/24322b8e-8953-40b9-9b0c-6d13a725a8c6)
While I was there, I also added the servo write "delay" as a parameter too. (the default value 30 isn't the best for my setup).

The three parameters are sent to the Arduino upon connection of the device in Nina. Please check how it's parsed on the Arduino side; it's a little dirty... (but it works :) )

I have no idea how I can properly share my code with you or if you're even interested. I'm simply attaching a ZIP below that contains both the driver and the Arduino file. Let me know if there is a better method.
[Motorized_cover_guillaume.zip](https://github.com/user-attachments/files/15865544/Motorized_cover_guillaume.zip)

Comments/critics very welcome!

-Guillaume

PS: Awesome job you did there! I already built two motorized covers, including one for my C11 and, despite the large size, it works perfectly.

**Comment by jlecomte** [comment]
Hello! Great work! Note that this project is now on life support so I will not make any changes to it. However, I have been working on a new version of this project, which brings a lot of improvements, and fixes the servo pulse min/max thing you mentioned. I do not have an ETA to release that project. Thanks!

**Comment by vef445** [comment]
> Hello! Great work! Note that this project is now on life support so I will not make any changes to it. However, I have been working on a new version of this project, which brings a lot of improvements, and fixes the servo pulse min/max thing you mentioned. I do not have an ETA to release that project. Thanks!

I’ll keep an eye on what’s coming next!
