### ISSUE TITLE
WriteProfile autoDetectComPort alway be true

### ISSUE THREAD

**Issue by ZetChang** [jlecomte/automated-telescope-dust-cover#3]
![image](https://github.com/jlecomte/ascom-telescope-cover/assets/60462095/29a8a150-5f84-493c-a0b0-c89d74aa37ae)

**Comment by jlecomte** [comment]
Good catch, thanks!

**Comment by jlecomte** [comment]
Fixed in https://github.com/jlecomte/ascom-telescope-cover/commit/37df01e01ec9c3148f8a7f52a69194fa1b1d81bb and release v1.0.1.

**Comment by ppurbano** [comment]
Hello. I love their projects and I have made both the flats generator and the telescope cover. I would like to ask you if it would be possible to join the two circuits into a single XIA0. It would be greatly appreciated. A strong greeting
