### ISSUE TITLE
2 servos instead of one ?

### ISSUE THREAD

**Issue by aras-vbo** [jlecomte/automated-telescope-dust-cover#4]
Hello Julien,

Vincent from France. Many thanks for your project ! I'm currently making a cover for my remote telescope.
This is just an idea. Is it possible to control 2 servos from the Xiao at the same time instead of one ? My telescope has a diameter of 250 mm and I'm not able to make a dust cap in just one piece. I need to use 2 parts in shapes of half-circle.
Do you think it could be difficult to add this feature, by changing the Xiao firmware only ?

I think I will try for fun !

Vincent

**Comment by jlecomte** [comment]
It is absolutely possible! I can imagine that one servo will start early and the second servo will follow shortly after, and there will be a small lip to overlap the two panels. Best of luck!
