### ISSUE TITLE
Control two covers from one computer?

### ISSUE THREAD

**Issue by OregonAstronomer** [jlecomte/automated-telescope-dust-cover#7]
Hi,
First, I'd like to thank you for this great project. It has been working flawlessly in my remote observatory for the past year!
I'm planning on adding a second camera with an attached telephoto lens piggyback on top of the scope I am currently using and would like to also equip it with one of your covers. Is it possible to control two covers using two instances of NINA from a single computer?
Thank you so much for your time.
Sincerely,
Arnie (OregonAstronomer)

**Comment by Adler6907** [comment]
I programmed an extension for exactly this.

https://github.com/Adler6907/ascom-telescope-cover/tree/Adler6907-multiple-Telescope-Cover

**Comment by jlecomte** [comment]
Yes, it is possible to control two covers using two instances of NINA on a single computer.

**Comment by OregonAstronomer** [comment]
Thank you both so much!
