### ISSUE TITLE
Added control (third state) to turn on flatpanel (and added COMMAND:FLAT in ARDUINO project), but...

### ISSUE THREAD

**Issue by thegoodpope** [jlecomte/automated-telescope-dust-cover#8]
...but i cannot regasm the assembly. 

My Visual Studio 2019 refuses to install as COM the resulting dll.
"RA0000 .... is not a valid assembly."
I'm a programmer but not expert with C# and Visual studio in general. Is there something I've to change in order to compile and install the driver?
I ask to you because:
1) I cannot find real and useful explanations. I've attempted to put signature, change GUID and a lot of other things
2) I cannot install - also - the compiled result of your original code
3) nevertheless the installation of your COM dll component (very useful your HUB also! Thank you) runs perfectly...so are there differences between the COM component you distribute and the project you share?

Thanks in every case for your project. I've customized the original cap/legs/base for my scope (a 20cm newton) and all went well.

**Comment by jlecomte** [comment]
> Is there something I've to change in order to compile and install the driver?

No. It should work out of the box. This, however, assumes that you already have the ASCOM platform installed on your development computer.
